### ISSUE TITLE
seems obs still need to be the focused application

### ISSUE THREAD

**Issue by allegfede** [streamduck-org/streamduck-gui#2]
I have to admit that i'm just experimenting with your app but seems very interesting.
Have not idea if my metod to simulate teh press of more than a button at the same time is ok (ctrl+shit+F_key) so i made 3 press event and 3 release events for the 3 keys, but seems that obs still needs to be on focus to get the inputs.

Do i need the websockets or not?

Thanks for your time.

Federico

**Comment by nedius** [comment]
Hello Federico

I'm not a developer, but i morally supporting him, so don't know any deep knowledge, but here what i think about this:

For obs to recognize global shortcuts you need to enable them, like in this thread https://obsproject.com/forum/threads/global-hotkeys.141455/.
But i think that better way would have streamduck integration to obs, like official app has (we need to wait for that to happen)

**Comment by TheJebForge** [comment]
So, keyboard emulation was made pretty half-arsed since the point is to have integration to the applications rather than relying on keyboard emulation to do the work. I really only included this in the project so there's at least something that can be used without use of plugins.

It's also already possible to implement OBS integration as a plugin since the plugin api is already pretty solid, it's just currently undocumented... I plan on continuing development of the software soon and after documenting plugin api, i'll be working on OBS integration myself

**Comment by allegfede** [comment]
Thanks for the kind reply.
Already checked the "global keystroke" setting in obs and is enabled.
So seems the problem is somewhere out.
PS: I'm using Wayland and I know this could be a problem.


Il sab 8 ott 2022, 17:15 TheJebForge ***@***.***> ha scritto:

**Comment by TheJebForge** [comment]
Wayland is probably a problem, I'm using libxdo to simulate keystrokes and as far as I know, it's for XOrg only

**Comment by TheJebForge** [comment]
Switched rails completely with streamduck

**Comment by TheJebForge** [comment]
Switched rails completely with streamduck
